package com.model;
// Generated 2016-5-28 20:34:30 by Hibernate Tools 5.1.0.Alpha1

/**
 * HospitalDepartment generated by hbm2java
 */
public class HospitalDepartment implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private int hid;
	private int depId;

	public HospitalDepartment() {
	}

	public HospitalDepartment(int id, int hid, int depId) {
		this.id = id;
		this.hid = hid;
		this.depId = depId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getHid() {
		return this.hid;
	}

	public void setHid(int hid) {
		this.hid = hid;
	}

	public int getDepId() {
		return this.depId;
	}

	public void setDepId(int depId) {
		this.depId = depId;
	}


}
