package com.model;
// Generated 2016-5-28 20:34:30 by Hibernate Tools 5.1.0.Alpha1

/**
 * Hospital generated by hbm2java
 */
public class Hospital implements java.io.Serializable {

	private int id;
	private String name;
	private String nature;
	private String region;
	private String level;
	private String type;
	private String address;
	private String telephone;
	private String web;
	private String describe;
	private String picture;

	public Hospital() {
	}

	public Hospital(int id, String name, String region) {
		this.id = id;
		this.name = name;
		this.region = region;
	}

	public Hospital(int id, String name, String nature, String region, String level, String type, String address,
			String telephone, String web, String describe, String picture) {
		this.id = id;
		this.name = name;
		this.nature = nature;
		this.region = region;
		this.level = level;
		this.type = type;
		this.address = address;
		this.telephone = telephone;
		this.web = web;
		this.describe = describe;
		this.picture = picture;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNature() {
		return this.nature;
	}

	public void setNature(String nature) {
		this.nature = nature;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

}
